/*Table structure for table `FILESTORAGE` */

CREATE TABLE `FILESTORAGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILEPATH` varchar(255) DEFAULT NULL,
  `ORIGNAME` varchar(255) DEFAULT NULL,
  `ANNOT` varchar(255) DEFAULT NULL,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `FILE_ID` int(11) DEFAULT NULL,
  `ENTITY_TYPE` int(11) DEFAULT NULL,
  `MIMETYPE` varchar(255) DEFAULT NULL,
  `SIZE` int(11) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `DT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
